---

#- name: configure interface e1/2 for Switch A
#  nxos_l3_interface:
#    name: Ethernet1/2
#    ipv4: "{{ ptp_ip }}"
#  
#- name: ensure point-to-point link is admin up
#  nxos_interface:
#    name: Ethernet1/2
#    admin_state: up
- name: configure loopback interface
  nxos_interface:
    name: Loopback1
    admin_state: up

- name: assign loopback ip address
  nxos_config:
    lines:
      - ip address 192.168.100.1/32
    parents:
      - interface Loopback1

- name: configure interface e1/1 for Switch B
  nxos_l3_interface:
    name: Ethernet1/1
    ipv4: "{{ l3_vpc_ip }}"
  
- name: ensure VPC L3 link is admin up
  nxos_interface:
    name: Ethernet1/1
    admin_state: up    
     
- name: configure interface for vlan 10
  nxos_config:
    lines: 
      - ip address 192.168.10.3/24
      - no shutdown
    parents:
      - interface vlan10
    
- name: configure interface for vlan 20
  nxos_config:
    lines: 
      - ip address 192.168.20.3/24
      - no shutdown
    parents:
      - interface vlan20

- name: configure interface for vlan 30
  nxos_config:
    lines: 
      - ip address 192.168.30.3/24
      - no shutdown
    parents:
      - interface vlan30