---

- name: configure upstream ports
  ios_config:
    match: none
    lines:
      - switchport
      - switchport mode trunk
      - no shutdown
    parents: "{{ item }}"
  loop:
    - interface TenGigabitEthernet1/1/1
    - interface TenGigabitEthernet1/1/2